C     This File is Automatically generated by ALOHA 
C     The process calculated in this file is: 
C     P(3,1) - P(3,2)
C     
      SUBROUTINE SSV1P1N_3(S1, S2, COUP,V3)
      IMPLICIT NONE
      COMPLEX*16 CI
      PARAMETER (CI=(0D0,1D0))
      COMPLEX*16 COUP
      REAL*8 P1(0:3)
      REAL*8 P2(0:3)
      COMPLEX*16 S1(*)
      COMPLEX*16 S2(*)
      COMPLEX*16 V3(6)
      P1(0) = DBLE(S1(1))
      P1(1) = DBLE(S1(2))
      P1(2) = DIMAG(S1(2))
      P1(3) = DIMAG(S1(1))
      P2(0) = DBLE(S2(1))
      P2(1) = DBLE(S2(2))
      P2(2) = DIMAG(S2(2))
      P2(3) = DIMAG(S2(1))
      V3(3)= COUP*S1(3)*S2(3)*(-CI*(P1(0))+CI*(P2(0)))
      V3(4)= COUP*S1(3)*S2(3)*(+CI*(P1(1))-CI*(P2(1)))
      V3(5)= COUP*S1(3)*S2(3)*(+CI*(P1(2))-CI*(P2(2)))
      V3(6)= COUP*S1(3)*S2(3)*(+CI*(P1(3))-CI*(P2(3)))
      END


